steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dashboard-automation:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dashboard-automation:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'dashboard-automation'
    - '--image'
    - 'gcr.io/$PROJECT_ID/dashboard-automation:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--timeout'
    - '3600'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'AUTOMATION_MODE=scheduler'

images:
  - 'gcr.io/$PROJECT_ID/dashboard-automation:$COMMIT_SHA'