steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/south-media-ia-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/south-media-ia-backend:latest',
      '-f', 'backend/Dockerfile.sheets',
      '.'
    ]

  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/south-media-ia-backend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/south-media-ia-backend:latest']

  # Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'south-media-ia-backend',
      '--image', 'gcr.io/$PROJECT_ID/south-media-ia-backend:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '3',
      '--timeout', '300'
    ]

# Configurações
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout
timeout: '1200s'
